import pygame
pygame.init()
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
player1_image = pygame.image.load("ادرس و نام عکس")
player1_rect = player1_image.get...
player1_rect.left = ....
player1_rect.bottom = ...

player2_image = pygame.image.load("ادرس و نام عکس")
player2_rect = player2_image.get...
player2_rect.right = ....
player2_rect.bottom = ...

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    keys = pygame.key.get_pressed()
    if keys[pygame.K_LEFT] and ...:
        player1_rect.x -= ...
    ......

    if keys[pygame.K_a] and ....:
        player2_rect.x -= ...
    ....
    screen.fill(...)
    screen.blit...
    screen.blit ...
    pygame.display.update()
